apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: simplenode
spec:
  gateways:
  - simpleproject-staging-gateway.simpleproject-staging
  - mesh
  hosts:
  - simplenode.simpleproject-staging.104.196.133.85.xip.io
  - simplenode
  http:
  - route:
    - destination:
        host: simplenode.simpleproject-staging.svc.cluster.local
